-include_lib("feed_server/include/records.hrl").

-define(ROOT, code:priv_dir(web)).
-define(DEFJS, "/static/js/countach.min.js").

-define(CSS,                "/static/css/countach.css").
-define(LESS,               "/static/less/countach.less").
-define(REVIEWS_CSS,        "/static/css/countach.css").
-define(REVIEWS_LESS,       "/static/less/countach.less").
-define(BOOTSTRAP,          ?DEFJS).
-define(REVIEWS_BOOTSTRAP,  ?DEFJS).
-define(INDEX_CSS,          "/static/css/countach.css").
-define(INDEX_LESS,         "/static/less/countach.less").
-define(INDEX_BOOTSTRAP,    ?DEFJS).
-define(LOGIN_BOOTSTRAP,    ?DEFJS).
-define(LOGIN_CSS,          "/static/css/countach.css").
-define(PRODUCT_CSS,        "/static/css/countach.css").
-define(PRODUCT_BOOTSTRAP,  ?DEFJS).
-define(MYREVIEW_CSS,       "/static/css/countach.css").
-define(MYREVIEW_BOOTSTRAP, ?DEFJS).
-define(DIRECT_CSS,         "/static/css/countach.css").
-define(DIRECT_BOOTSTRAP,   ?DEFJS).
-define(ADMIN_CSS,          "/static/css/countach.css").
-define(ADMIN_BOOTSTRAP,    ?DEFJS).
-define(PROFILE_CSS,        "/static/css/countach.css").
-define(PROFILE_BOOTSTRAP,  ?DEFJS).
-define(CART_CSS,           "/static/css/countach.css").
-define(CART_BOOTSTRAP,     ?DEFJS).
-define(CHECKOUT_CSS,       "/static/css/countach.css").
-define(CHECKOUT_BOOTSTRAP, ?DEFJS).
-define(STORE_CSS,          "/static/css/countach.css").
-define(STORE_BOOTSTRAP,    ?DEFJS).
-define(MYGAMES_CSS,        "/static/css/countach.css").
-define(MYGAMES_BOOTSTRAP,  ?DEFJS).
-define(REVIEW_CSS,         "/static/css/countach.css").
-define(REVIEW_BOOTSTRAP,   ?DEFJS).

-define(PAGE_SIZE, 4).
-define(BTN_INFO,       [btn, "btn-info"]).
-define(BTN_SUCCESS,    [btn, "btn-success"]).
-define(STACK_BASE,     ["icon-stack-base", "icon-circle"]).
-define(DATA_TOOLTIP,   [{<<"data-toggle">>,<<"tooltip">>}]).
-define(DATA_TAB,       [{<<"data-toggle">>,<<"tab">>}]).
-define(DATA_AFFIX,     [{<<"data-spy">>,<<"affix">>}]).
-define(DATA_DROPDOWN,  [{<<"data-toggle">>,<<"dropdown">>}]).
-define(DATA_PILL,      [{<<"data-toggle">>,<<"pill">>}]).
-define(DATA_COLLAPSE,  [{<<"data-toggle">>, <<"collapse">>}, {<<"data-target">>, <<".navbar-collapse">>}]).
-define(DATA_OFFCANVAS, [{<<"data-toggle">>, <<"offcanvas">>}]).
-define(URL_PRODUCT(Id),"/product?id="++wf:to_list(Id)).
-define(URL_REVIEW(Id), "/review?id="++wf:to_list(Id)).
-define(URL_PROFILE(Id),"/profile?id="++wf:to_list(Id)).
-define(URL_AVATAR(Url, Size),  iolist_to_binary([case Url of undefined-> "holder.js/"++Size++"x"++Size;_-> Url end,
                                "?sz=",Size,"&width=",Size,"&height=",Size,"&s=",Size])).

-record(struct,         {lst=[]}).
-record(product_hero,   {?ELEMENT_BASE(product), product}).

-define(USR_CART(Id),   wf:to_list(erlang:phash2(Id))++"cart").
-define(USR_ORDER(Id),  wf:to_list(erlang:phash2(Id))++"order").
-define(FD_CHKOUT(Id),  wf:to_list(Id)++"chk").
-define(PAGE_ALERT(Id), wf:to_list(erlang:phash2(Id))++"alt").
